name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "*/360 * * * *"
  push:
    branches:
      - main
    paths-ignore: 
      - "**/README.md" 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - name: Prepare Workstation
        shell: bash
        run: |
          git config --global init.defaultBranch main
          mkdir publish
          
      - name: build no-cn list
        run: |
          export proxy=publish/proxy.txt
          curl -L 'https://raw.githubusercontent.com/v2fly/domain-list-community/release/geolocation-!cn.txt' | sed '/[@ads@cn]$/d' | sed '/^regexp/d' > $proxy
          sed -i 's/domain\:/DOMAIN\-SUFFIX,/' $proxy
          sed -i 's/full\:/DOMAIN,/' $proxy
          
      - name: build china ip list
        run: |
           curl -L https://raw.githubusercontent.com/carrnot/china-ip-list/release/ip.txt | sed 's/^/IP\-CIDR\,/' > publish/direct-ip.txt
           
      - name: build china domain list
        run: |
          curl -L https://raw.githubusercontent.com/carrnot/china-domain-list/release/domain.txt | sed 's/^/DOMAIN\-SUFFIX\,/' > publish/direct-name.txt

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git checkout -b release
          git add --all
          git commit -m "sync"
          git remote add shadowrocket-rules "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f shadowrocket-rules release
